@makeBaseMeasure Current Ampere "A"
@makeBaseMeasure Intensity Candela "cd"
@makeBaseMeasure Length Meter "m"
@makeBaseMeasure Mass KiloGram "kg"
@makeBaseMeasure Temperature Kelvin "K"
@makeBaseMeasure Time Second "s"